export function RandomHelper() {}
RandomHelper.prototype.firstNameList = [
    "ZHIYUAN",
    "CHIIJUN",
    "YUZE",
    "HUALEI",
    "SHENGRUI",
    "TIANYOU",
    "WENHAO",
    "XIUJIE",
    "LIXI",
    "YUANHANG",
    "XUYAO",
    "HONGTAO",
    "WEIQI",
    "RONGXUAN",
    "YUEZE",
    "HAOYU",
    "JINYU",
    "HAOXUAN",
    "JINCANG",
    "ZHIZE",
    "ZIXUAN",
    "RUIYUAN",
    "HONGWEN",
    "ZHEHAN",
    "YUZE",
    "KAIRUI",
    "JIANHUI",
    "JINPENG",
    "TIANLEI",
    "SHAOHUI",
    "ZEYANG",
    "XINLEI",
    "PENGXUAN",
    "HAOQIANG",
    "YANBIN",
    "HEXUAN",
    "FENGHUA",
    "JINKJI",
    "MINGHUI",
    "WEICHENG",
    "MINGXUAN",
    "JIANBO",
    "XIUJIE",
    "YUANBO",
    "ZHENGHAO",
    "LIHUI",
    "ZHICHENG",
    "HAORAN",
    "LICHENG",
    "JUNXI",
    "MENGQI",
    "ZHITAO",
    "MUQING",
    "ERLUAN",
    "CHUXIA",
    "PEIHAN",
    "AOSHAN",
    "MANWEN",
    "LIJIA",
    "LEMAI",
    "XIWEN",
    "HANXIANG",
    "XINRONG",
    "ZUILAN",
    "YUQIN",
    "CHONGBIN",
    "YULAN",
    "YUHAN",
    "YIYAN",
    "RUXUAN",
    "RUONAN",
    "MULIN",
    "YIRUI",
    "XUELIU",
    "YINGYI",
    "HAIYUN",
    "YINGTIAN",
    "FANQIN",
    "DANZHEN",
    "JINGMAN",
    "DAIYUN",
    "YOUCUI",
    "BINLU",
    "WANBAI",
    "YUZHEN",
    "HUANSI",
    "MIFENG",
    "XIAOXIANG",
    "SHANLIU",
    "GUXUE",
    "LINGXUE",
    "HANYU",
    "DAISHAN",
    "YIDAN",
    "BIYU",
    "FEIYANG",
    "HAIYANG",
    "BAIMING",
    "YOURONG",
    "WENXIA",
    "NANQING",
    "MENGHAN",
    "ZHUNAN",
    "NANA",
    "LINGQING",
    "QIULIU",
    "MANYU",
    "JIAXIN",
    "XIAOXUN",
    "LIJUN",
    "MIYUN",
    "GUKUI",
    "LERUI",
    "AOWEI",
    "MANLAN",
    "YINGLING",
    "XIAZHEN",
    "JINFENG",
    "LESHUANG",
    "WENYU",
    "YUANFANG",
    "XUELIAN",
    "HONGLEI",
    "GURONG",
    "YINGDONG",
    "LIJING",
    "BANLAN",
    "MEIMEI",
    "MEILING",
    "XIAOTIAN",
    "PINGFAN",
    "SHIHUAI",
    "PINGSONG",
    "YISONG",
    "PEISHAN",
    "XIAOLU",
    "NIANMENG",
    "YANSHI",
    "XINQING",
    "CAISHAN",
    "CAICHI",
    "XIHAN",
    "BINGHAI",
    "NANSHUANG",
    "CAIBO",
    "QIANFAN",
    "YIQING",
    "ZHANGUI",
    "CHANGKUI",
    "LENGYU",
    "ZHISHAN",
    "ZHIJING",
    "LIJUAN",
    "JUN",
    "JU",
    "FANG",
    "LILI",
    "LINA",
    "LIULIU",
    "GUANYU",
    "FENGFEI",
    "BAIMEI",
    "SHUIFENG",
    "JIPING",
    "MENGZHU",
    "JIQING",
    "LIANGJIN",
    "XUEHUI",
    "SHICUI",
    "DONGYI",
    "SHANDIE",
    "QIYAN",
    "FANGBAI",
    "GAOHU",
    "XIADAN",
    "YUTING",
    "JIJUN",
    "NIANZHI",
    "RUNZHI",
    "PINGAN",
    "HANQIAO",
    "XIER",
    "FENLAN",
    "XIANGLU",
    "XIAOQIANG",
    "XIAOJUN",
    "XIAOFANG",
    "YUMEI",
    "XIANGZHEN",
    "YIYUN",
    "DANYU",
    "XIAOQIN",
    "XIANGTONG",
    "QINGSHAN",
    "QINGQING",
    "XIAOQING",
    "HANHANG",
    "DAHAI",
    "WENFENG",
    "WEIWEI ",
    "XIAOLIN",
    "XIAOHUA",
    "SIHU",
    "GUANGHUA",
    "ERGOU",
    "YIFA",
    "MINGZI",
    "ZIHAN",
    "XIAOMENG",
    "XIAOPIN",
    "ZEDONG",
    "JINTAO",
    "JINPING",
    "JIABAO",
    "BAO",
    "JIA",
    "YONGHANG",
    "YONGKANG",
    "YONGQI",
    "GEGE",
    "LULU",
    "MENGFEI",
    "ERBU",
    "LONG",
    "MAIJIN",
    "GUKE",
    "SANMING",
    "XIAOBU",
    "AIQING",
    "GONGYU",
    "SHENQI",
    "GUANGU",
    "MEIJIA",
    "ZIQIAO",
    "ZIMO",
    "MOMO",
    "DACHUI",
    "ZHONGTIAN",
    "HAIMENG",
    "SHANGLV",
    "YOUYI",
    "HUAXIA",
    "HUA",
    "TIAN",
    "AOMEN",
    "MANGU",
    "SHANTIAN",
    "BAIYU",
    "HE",
    "DONGLU",
    "TAO",
    "CHAO",
    "ZICHAO",
    "ZITAO",
    "DUMIN",
    "LAN",
    "ZHITAO",
    "LILI",
    "FENGHUA",
    "TAOGU",
    "ZIGU",
    "SHANGXIN",
    "MENGHUA",
    "YUANSHEN",
    "XIAYU",
    "ZIQING",
    "LISHA",
    "YUANHE",
    "DUSHAN",
    "DUAN",
    "ZHIZI",
    "HUAMEI",
    "BAIHE",
    "BAILU",
    "FUYUAN",
    "TISHENG",
    "AIQIN",
    "HUATEN",
    "TENGYU",
    "SHIYI",
    "LOU",
    "LUOYONG",
    "YONGHAO",
    "LUOHAO",
    "SIYU",
    "YUZHOU",
    "ZHENYU",
    "ZHENHUA",
    "ZHENSHENG",
    "DENGQI",
    "DANYU",
    "QIANGHE",
    "FUZHI",
    "YISHENG",
    "MAIQI",
    "YINSHUI",
    "HUANGHE",
    "CHANGJIANG",
    "YALU",
    "BINGTANG",
    "BING",
    "TANG",
    "XUE",
    "LI",
    "XUELI",
    "GE",
    "LI",
    "KONG",
    "TIAO",
    "GELI",
    "KONGTIAO",
    "KUAI",
    "LE",
    "QI",
    "TIAN",
    "KUAILE",
    "QITIAN",
    "QILE",
    "WUKONG",
    "WU",
    "WUNENG",
    "NENG",
    "FAN",
    "JING",
    "FANJING",
    "JUNHUA",
    "SHENGMING",
    "BEI",
    "JI",
    "TA",
    "SHUKE",
    "BEITA",
    "BAIER",
    "XIONGDI",
    "PENGYOU",
    "YONG",
    "KANG",
    "SHUMA",
    "BAOBEI",
    "ZI",
    "SHU",
    "YIN",
    "MOU",
    "SHEN",
    "YOUI",
    "HAI",
    "WU",
    "JIA",
    "SHU",
    "GEN",
    "BEN",
    "TINGBU",
    "XIA",
    "LAI"
];
RandomHelper.prototype.lastNameList = [
    "ZHAO",
    "QIAN",
    "SUN",
    "LI",
    "ZHOU",
    "WU",
    "ZHENG",
    "WANG",
    "FENG",
    "CHEN",
    "CHU",
    "WEI",
    "JIANG",
    "SHEN",
    "HAN",
    "YANG",
    "ZHU",
    "QIN",
    "YOU",
    "XU",
    "HE",
    "LU",
    "SHI",
    "ZHANG",
    "KONG",
    "CAO",
    "YAN",
    "HUA",
    "JIN",
    "WEI",
    "ZOU",
    "YU",
    "BAI",
    "SHUI",
    "DOU",
    "GE",
    "XI",
    "FAN",
    "PENG",
    "LANG",
    "WEI",
    "CHANG",
    "MA",
    "MIAO",
    "FENG",
    "HUA",
    "FANG",
    "YU",
    "REN",
    "YUAN",
    "LIU",
    "FENG",
    "BAO",
    "SHI",
    "TANG",
    "FEI",
    "LIAN",
    "CEN",
    "XUE",
    "LEI",
    "HE",
    "NI",
    "FENG",
    "YIN",
    "LUO",
    "BI",
    "HAO",
    "WU",
    "AN",
    "CHANG",
    "YUE",
    "YU",
    "SHI",
    "FU",
    "PI",
    "BIAN",
    "QI",
    "KANG",
    "YAO",
    "SHAO",
    "ZHAN",
    "WANG",
    "QI",
    "MAO",
    "DI",
    "MI",
    "BEI",
    "MING",
    "ZANG",
    "JI",
    "FU",
    "CHENG",
    "DAI",
    "TAN",
    "SONG",
    "MAO",
    "PANG",
    "XIONG",
    "JI",
    "SHU",
    "QU",
    "XIANG",
    "ZHU",
    "DONG",
    "LIANG",
    "DU",
    "RUAN",
    "LAN",
    "MIN",
    "XI",
    "JI",
    "MA",
    "QIANG",
    "JIA",
    "LU",
    "LOU",
    "WEI",
    "JIANG",
    "TONG",
    "YAN",
    "GUO",
    "MEI",
    "SHENG",
    "LIN",
    "DIAO",
    "ZHONG",
    "XU",
    "QIU",
    "LUO",
    "GAO",
    "XIA",
    "CAI",
    "TIAN",
    "FAN",
    "HU",
    "LING",
    "HUO",
    "WAN",
    "ZHI",
    "KE",
    "ZAN",
    "GUAN",
    "LU",
    "MO",
    "JING",
    "FANG",
    "QIU",
    "MIAO",
    "GAN",
    "XIE",
    "YING",
    "ZONG",
    "DING",
    "XUAN",
    "BEN",
    "DENG",
    "SHAN",
    "HANG",
    "HONG",
    "BAO",
    "ZHU",
    "ZUO",
    "GONG",
    "CHENG",
    "JI",
    "RONG",
    "WENG",
    "XUN",
    "YANG",
    "HUI",
    "QU",
    "JIA",
    "FENG",
    "RUI",
    "YI",
    "CHU",
    "JIN",
    "JI",
    "BING",
    "MI",
    "SONG",
    "JING",
    "DUAN",
    "FU",
    "WU",
    "JIAO",
    "BA",
    "GONG",
    "MU",
    "KUI",
    "SHAN",
    "GU",
    "CHE",
    "HOU",
    "PENG",
    "QUAN",
    "XI",
    "BAN",
    "YANG",
    "QIU",
    "ZHONG",
    "GONG",
    "NING",
    "JING",
    "LONG",
    "YE",
    "BO",
    "YIN",
    "SU",
    "BAI",
    "HUAI",
    "PU",
    "TAI",
    "CONG",
    "E",
    "SUO",
    "XIAN",
    "JI",
    "LAI",
    "ZHUO",
    "LIN",
    "TU",
    "MENG",
    "CHI",
    "QIAO",
    "YU",
    "XU",
    "NAI",
    "CANG",
    "SHUANG",
    "WEN",
    "SHEN",
    "DANG",
    "ZHAI",
    "TAN",
    "GONG",
    "LANG",
    "PANG",
    "SHEN",
    "FU",
    "DU",
    "RAN",
    "ZAI",
    "YONG",
    "XI",
    "QU",
    "SANG",
    "TONG",
    "BIAN",
    "HU",
    "YAN",
    "JI",
    "JIA",
    "PU",
    "SHANG",
    "NONG",
    "WEN",
    "BIE",
    "ZHUANG",
    "YAN",
    "CHAI",
    "SHEN",
    "GE",
    "LIAO",
    "ZHONG",
    "HENG",
    "BU",
    "GUO",
    "WEN",
    "KOU",
    "GUANG",
    "LU",
    "QUE",
    "DONG",
    "OU",
    "SHU",
    "LI",
    "WEI",
    "YUE",
    "KUI",
    "NONG",
    "HUAN",
    "GONG",
    "SHANG",
    "MOU",
    "SHE",
    "NAI",
    "MO",
    "HA",
    "QIAO",
    "DA",
    "NIAN",
    "AI",
    "MU",
    "HE",
    "NENG",
    "YI",
    "XUN",
    "MAI"
];
// lowercase it
// RandomHelper.prototype.firstNameList = RandomHelper.prototype.firstNameList.map(function(item) {
// 	return item.toLowerCase()
// })
// console.log(RandomHelper.prototype.firstNameList)
RandomHelper.prototype.emailDomainList = ["gmail.com", "yahoo.com", "hotmail.com", "outlook.com", "qq.com", "163.com", "live.cn", "live.com"];
RandomHelper.prototype.randomPeopleList = function (count: any) {
    var self = this;
    var list = [];
    while (count--) {
        list.push(self.randomPeople());
    }
    return list;
};
RandomHelper.prototype.randomPeople = function () {
    var self = this;
    var firstNameList = self.firstNameList;
    var lastNameList = self.lastNameList;
    var emailDomainList = self.emailDomainList;
    var people: any = {
        title: undefined,
        firstName: undefined,
        lastName: undefined,
        birthDateYear: undefined,
        birthDateMonth: undefined,
        birthDateDay: undefined,
        birthday: undefined,
        email: undefined,
        nationality: undefined,
        phoneNo: undefined
    };
    people.title = randomTitle();
    people.firstName = randomFirstName();
    people.lastName = randomLastName();
    people.birthday = randomBirthday();
    people.email = randomEmail();
    people.nationality = randomNationality();
    people.phoneNo = randomPhoneNo();
    return people;
    function randomTitle() {
        return "MR";
    }
    function randomFirstName() {
        while (true) {
            var n = range(0, firstNameList.length);
            if (/^[a-cA-C]/.test(firstNameList[n]) === false) break;
        }
        return firstNameList[n];
    }
    function randomLastName() {
        while (true) {
            var n = range(0, lastNameList.length);
            if (/^[a-cA-C]/.test(lastNameList[n]) === false) break;
        }
        return lastNameList[n];
    }
    function randomBirthday() {
        // 1965-01-01 后 20 年间的某一天
        var d = new Date(1965, 0, 1).valueOf();
        var delta = range(0, 20 * 365 * 24 * 60 * 60 * 1000);
        return new Date(d + delta);
    }
    function randomEmail() {
        var firstName = people.firstName.toLowerCase().replace(/\s+/g, "");
        var lastName = people.lastName.toLowerCase().replace(/\s+/g, "");
        var prefix = lastName + firstName;
        var postfix = emailDomainList[range(1, emailDomainList.length)];
        return prefix + "@" + postfix;
    }
    function randomNationality() {
        return "CN";
    }
    function randomPhoneNo() {
        var head_list = ["139", "138", "137", "136", "135", "134", "159", "150", "151", "158", "157", "188", "187", "152", "182", "147"];
        var head = head_list[range(0, head_list.length)];
        var body = "";
        for (var i = 0; i < 8; ++i) {
            body += range(1, 10); // 避免出现 0
        }
        return head + body;
    }
    function range(min: number, max: number) {
        return parseInt(x(min, max) as any);
        function x(min: number, max: number): number {
            var v = Math.random() * max;
            return v < min ? x(min, max) : v;
        }
    }
};
